name: yathra_employee
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  dio: ^4.0.0
  cached_network_image: ^3.1.0
  flutter_easyloading: ^3.0.3
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.5
  path: ^1.8.0
  path_provider: ^2.0.9
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  build_runner: ^2.1.10
  drift_dev: ^1.5.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

